[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_tools"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.10.0"
rand_distr = "0.6.0"
pyo3 = { version = "0.28.2", features = ["extension-module", "abi3-py310"] }