[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "signal_generator"
version = "0.1.0"
requires-python = ">=3.10"

[tool.maturin]
module-name = "signal_generator"
